baseURL = "https://example.com"
languageCode = "en-us"
title = "Archie Catppuccin Demo"
theme="archie-catppuccin-style"
copyright = "Â© Ethan Oliver Troy"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="toggle"
	catppuccinFlavor = "mocha"  # Options: latte, frappe, macchiato, mocha
	useCDN=false
	subtitle = "A demonstration of the Archie Catppuccin Hugo theme"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ethanolivertroy"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
